baseURL: "https://nasimbio.github.io/bioinfo-blog/"
languageCode: "en-us"
title: "Bioinformatics Blogs By Nasim Rahmatpour"
publishDir: "docs"

theme: hugo-lithium
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/nasimbio
    - name: LinkedIn
      url: https://www.linkedin.com/in/nasimrahmatpour/
params:
  author: "Nasim Rahmatpour"
  description: "Bioinformatics blog by Nasim Rahmatpour"
  github: "https://github.com/nasimbio"
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
