baseURL = "https://nasimbio.github.io/bioinfo-blog/"
languageCode = "en-us"
title = "Bioinformatics Blogs By Nasim"
publishDir = "docs"
theme = "hugo-paper"

[params]
  name = "Bioinformatics Blog by Nasim"

  bio = """Welcome ðŸ‘‹

Hi, Iâ€™m Nasim Rahmatpour, a bioinformatics scientist working on genomics, transcriptomics, single-cell, spatial, and multi-omic data analysis.

I use this blog to document the topics Iâ€™m learning and working on. I try to break down key concepts into simple, tutorial-style explanation. My goal is to build a foundation of clear, accessible notes that help me and others to better understand fundamental bioinformatics topics.

Writing here helps me focus, organize my thoughts, and remember key concepts better.

Below youâ€™ll find my posts and notes as I explore these areas.
"""

  github = "nasimbio"
  linkedin = "nasimrahmatpour"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about/"

  [[menu.main]]
    name = "GitHub"
    url  = "https://github.com/nasimbio"

  [[menu.main]]
    name = "LinkedIn"
    url  = "https://www.linkedin.com/in/nasimrahmatpour/"
